NB Classifier Weather\
Libraries: sklearn

Step1: Import necessary library

Step2: Prepare dataset

Step3: Digitize the dataset using encoding

Step4: Merge different features to prepare dataset

Step5: Train Naive Bayes Classifier

Step6: Predict output for new data

https://www.tutorialspoint.com/scikit_learn/scikit_learn_multinomial_naive_bayes.htm

# **1_NB_Classifier_Weather**

In [ ]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB , MultinomialNB 

In [ ]:
#Prepare dataset
weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast','Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']
temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [ ]:
#Digitize the dataset using encoding.
#Create labelEncoder -----> check onehot encoding
le=preprocessing.LabelEncoder()

#convert string labels into numbers.
weather_encoded = le.fit_transform(weather)
temp_encoded = le.fit_transform(temp)
label_encoded = le.fit_transform(play)



In [ ]:
#print encoded data
print("Weather: ", weather_encoded)
print("Temperature: ", temp_encoded)
print("Play class label: ", label_encoded)

Weather:  [2 2 0 1 1 1 0 2 2 1 2 0 0 1]
Temperature:  [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Play class label:  [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [ ]:
#Merge different features to prepare dataset

#combining weather and temp into single listof tuples
features = tuple(zip(weather_encoded, temp_encoded))

In [ ]:
#Print merged feature
print("Features: ", features)

Features:  ((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))


In [ ]:
#Train Naive Bayes Classifier
#create a classifier
model = MultinomialNB()

In [ ]:
#Train the model using training dataset
model.fit(features,label_encoded)

MultinomialNB()

In [ ]:
#Predict output for new data
predicted = model.predict([[0,2]]) # 0->overcast 1->mild
print("Predicted value for (overcast,mild) ",predicted)
predicted = model.predict([[0,1]])
print("Predicted value for (overcast,hot) ",predicted)
predicted = model.predict([[2,2]])
print("Predicted value for (sunny,mild) ",predicted)


Predicted value for (overcast,mild)  [1]
Predicted value for (overcast,hot)  [1]
Predicted value for (sunny,mild)  [1]


# **pdf 3_2 Exercise 3 questions 1 and 2**

In [34]:
#What will be the value of Play, if Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Nor-
#mal’, and Wind = ’False’?
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from google.colab import drive
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset/Naive Bayes/Dataset1.csv')
one_hot = pd.get_dummies(dataset, columns=['Outlook','Temp','Humidity','Wind','Play'])
print(one_hot)
#extract feature and label
#In pandas, the axis parameter specifies the dimension of the DataFrame or Series that you want to operate on.
##In particular, axis=1 refers to the columns of a DataFrame, while axis=0 refers to the rows of a DataFrame.
#When you call the drop method on a DataFrame with axis=1, it means you want to drop one or more columns
# from the DataFrame.
features = one_hot.drop(['Play_N', 'Play_Y'], axis=1)
label = one_hot[['Play_N','Play_Y']].values[:, 0]
model = MultinomialNB()
model.fit(features, label)


#predict value
new_data = pd.DataFrame({
    'Outlook_O': [0],
    'Outlook_R': [1],
    'Outlook_S': [0],
    'Temp_C': [0],
    'Temp_H': [1],
    'Temp_M': [0],
    'Humidity_High': [0],
    'Humidity_Low': [0],
    'Humidity_Normal':[1],
    'Wind_F': [1],
    'Wind_T': [0]
})
predicted = model.predict(new_data)
print('predicted is ',predicted)
print('Probability', model.predict_proba(new_data))

#What will be the value of Play, if Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity =’High’,
#and Wind = ’True’?
new_data = pd.DataFrame({
    'Outlook_O': [0],
    'Outlook_R': [0],
    'Outlook_S': [1],
    'Temp_C': [1],
    'Temp_H': [0],
    'Temp_M': [0],
    'Humidity_High': [1],
    'Humidity_Low': [0],
    'Humidity_Normal':[0],
    'Wind_F': [0],
    'Wind_T': [1]
})
predicted = model.predict(new_data)
print('predicted is ',predicted)
print('Probability', model.predict_proba(new_data))


#for model accuracy split data into train and test set
data_train, data_test, target_train, target_test = train_test_split(features,label,test_size = 0.2 , random_state=42)
model.fit(data_train,target_train)
pred = model.predict(data_test)
accuracy = accuracy_score(target_test, pred)
print("Accuracy:", accuracy)


precision = precision_score(target_test, pred)
recall = recall_score(target_test, pred)


print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

    Outlook_O  Outlook_R  Outlook_S  Temp_C  Temp_H  Temp_M  Humidity_High  \
0           0          1          0       0       1       0              0   
1           0          1          0       0       1       0              1   
2           1          0          0       0       1       0              0   
3           0          0          1       0       0       1              0   
4           0          0          1       1       0       0              0   
5           0          0          1       1       0       0              0   
6           1          0          0       1       0       0              0   
7           0          1          0       0       0       1              0   
8           0          1          0       1       0       0              0   
9           0          0          1       0       0       1              1   
10          0          1          0       0       0       1              1   
11          1          0          0       0       0       1     

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


This warning message indicates that precision could not be computed because there were no predicted samples in one or more of the classes. This can happen when the model is not able to predict any samples for a particular class, either because there are no samples of that class in the test set or because the model is not able to distinguish between that class and others.

To address this warning, you can set the zero_division parameter to a non-zero value when calling the precision function. This parameter determines the value to use for precision when there are no predicted samples in a class. For example, you could set zero_division=1 to treat precision as 1.0 when there are no predicted samples in a class. However, keep in mind that this may not be a meaningful value if there are actually samples of that class in the test set. Alternatively, you can try adjusting the model or the data to improve its ability to distinguish between classes.

# **2_NB_Classifier_Iris_2Classes**

Iris Dataset is a part of sklearn library. Sklearn comes loaded with datasets to practice machine learning techniques and iris is one of them. Iris has 4 numerical features and a tri class target variable. This dataset can be used for classification as well as clustering.

Iris dataset contains five columns such as Petal Length, Petal Width, Sepal Length, Sepal Width and Species Type. Iris is a flowering plant

In [ ]:
#import scikit-learn library
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

In [ ]:
#Load datasets
iris = datasets.load_iris()

In [ ]:
#Print the name of the features
print("Features :",iris.feature_names)

In [ ]:
#Print the class label type
print("Labels : ", iris.target_names)

The shape of the dataset means to print the total number of rows or entries and the total number of columns or features of that particular dataset.

In [ ]:
#print data(feature) shape:
print("DataShape: ", iris.data.shape)

DataShape:  (150, 4)


In [ ]:
#print target shape
print("Target shape: ", iris.target.shape)

Target shape:  (150,)


In [ ]:
#Print data
print("Data", iris.data)

In [ ]:
#Print target 
print("Target: ", iris.target)

In [ ]:
newdata = iris.data[50:,:]
newtarget = iris.target[50:]

In [ ]:
# print data(feature)shape
print("\nNew Data shape: ",newdata.shape)
#print data(target)shape
print("\nNew Target shape: ",newtarget.shape)

The train_test_split function randomly splits the data into two sets: X_train and X_test. We specified the test_size parameter to be 0.3, which means that 30% of the data will be used for the test set, and 70% of the data will be used for the training set.

Now, suppose we want to split the data again, but this time using a different random state. We can set the random state to a different value, like 123.

By setting the random state, we can ensure that the same random split is generated every time we run the code. This can be useful for testing and comparing different models, as we can ensure that the same data is used every time we train and test the model.

In [ ]:
#import the necessary module
from sklearn.model_selection import train_test_split
#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(newdata,
newtarget, test_size = 0.30, random_state = 5)

In [ ]:
import numpy as np
gnb = GaussianNB()
#train the model using training sets.
gnb.fit(data_train,target_train)

#predict the response for test dataset
target_pred = gnb.predict(data_test)

In [ ]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

#model accuracy, how often s the classifier correct?
print("Accuracy:", metrics.accuracy_score(target_test,target_pred))

Accuracy: 0.9


In [ ]:
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[16,  1],
       [ 2, 11]])

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred)
recall = recall_score(target_test, target_pred)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: 0.8888888888888888
recall: 0.9411764705882353


# 3_NB_Classifier_Iris_3Classes

In [ ]:
#Import scikit-learn dataset library
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
#Load dataset
iris = datasets.load_iris()

In [ ]:
# print the names of the 13 features
print("Features: ", iris.feature_names)
# print the label type of wine(class_0, class_1, class_2)
print("Labels: ", iris.target_names)
# print data(feature)shape
iris.data.shape

Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Labels:  ['setosa' 'versicolor' 'virginica']


(150, 4)

In [ ]:
#import the necessary module
from sklearn.model_selection import train_test_split
#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(iris.data,
iris.target, test_size = 0.30, random_state = 10)

Suppose we have a small dataset of 10 numbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]. We want to randomly split this dataset into two sets: a training set and a test set. We can use the train_test_split function from scikit-learn library to do this.

The train_test_split function randomly splits the data into two sets: X_train and X_test. We specified the test_size parameter to be 0.3, which means that 30% of the data will be used for the test set, and 70% of the data will be used for the training set.

Now, suppose we want to split the data again, but this time using a different random state. We can set the random state to a different value, like 123.

In [ ]:
import numpy as np
gnb = GaussianNB()
#Train the model using the training sets
gnb.fit(data_train, target_train)
#Predict the response for test dataset
target_pred = gnb.predict(data_test)
target_pred

array([1, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2, 1, 1, 2, 2, 2, 0, 2, 2, 2, 2, 0, 0, 1, 0,
       1])

In [ ]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 1.0


In [ ]:
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[14,  0,  0],
       [ 0, 17,  0],
       [ 0,  0, 14]])

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1. 1. 1.]
recall: [1. 1. 1.]


# Exercise
1 <= Rollnumber <= 25: #Task 1: Try the algo on Dataset1 - OneHotEncoding of features:
and Train test Division 70%-30%

Task 2: Apply algorithm on digits dataset - LabelEncoding of features: and Train test Divi-
sion 80% − 20%

In [ ]:
#import libraries
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

In [ ]:
#prepare dataset
from google.colab import drive
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset/Naive Bayes/Dataset1.csv')
print("Data :- \n",dataset)
print("Data Statistics :- \n",dataset.describe())

One hot encoding is a process of representing categorical variables as binary vectors, where each vector has a dimension equal to the number of possible categories. In this representation, each category is assigned a unique binary code, where all dimensions of the binary vector are 0, except for the one corresponding to the category, which is set to 1.

For example, suppose we have a categorical variable called color with three possible categories: "red", "green", and "blue". One hot encoding would transform this variable into three binary vectors:


red:   [1, 0, 0]
green: [0, 1, 0]
blue:  [0, 0, 1]


In [ ]:
one_hot = pd.get_dummies(dataset, columns=['Outlook','Temp','Humidity','Wind','Play'])
one_hot